/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Client_ID]
      ,[Name]
      ,[Age]
      ,[Sex]
      ,[Location_ID]
      ,[Joined_Bank]
      ,[Banking_Contact]
      ,[Nationality]
      ,[Occupation]
      ,[Investment_Advisor]
      ,[Fee_Structure]
      ,[Loyalty_Classification]
      ,[Banking_Relationship]
      ,[Estimated_Income]
      ,[Superannuation_Savings]
      ,[Amount_of_Credit_Cards]
      ,[Credit_Card_Balance]
      ,[Bank_Loans]
      ,[Bank_Deposits]
      ,[Checking_Accounts]
      ,[Saving_Accounts]
      ,[Foreign_Currency_Account]
      ,[Business_Lending]
      ,[Properties_Owned]
      ,[Risk_Weighting]
  FROM [banking(final)].[dbo].[banking_fact]